<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <IsBindingProject>true</IsBindingProject>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <PackageId>JavaGl.Obj</PackageId>
    <PackageVersion>0.4.0.2</PackageVersion>
    <Owners>Taras Shevchuk</Owners>
    <Authors>Taras Shevchuk</Authors>
    <PackageIcon>icon.png</PackageIcon>
    <Summary>JavaGl.Obj bindings library</Summary>
    <Title>JavaGl.Obj</Title>
    <Description>JavaGl.Obj bindings library</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Saratsin/JavaGl.Obj</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>Obj, JavaGl, Android, Xamarin</PackageTags>
  </PropertyGroup>

   <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>

    <DesignTimeBuild>false</DesignTimeBuild>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup> 

  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>